from https://github.com/pintman/midi2mqtt

corrects an error message for Callback api in python 3
